
DEBUG = true
SECRET_KEY = "for-prod-insert-a-random-string-here"
ALLOWED_HOSTS = ["*"]
INTERNAL_IPS = ["127.0.0.1"]
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

[DATABASES.default]
ENGINE = 'django.db.backends.sqlite3'
NAME = 'C:/path/to/cfc-www.github/x-dev/environments/dev/db.default.sqlite3'

[STORAGES.default]
BACKEND = "django.core.files.storage.FileSystemStorage"

[STORAGES.staticfiles]
BACKEND = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
# ManifestStaticFilesStorage is recommended in production, to prevent
# outdated JavaScript / CSS assets being served from cache
# (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/5.0/ref/contrib/staticfiles/#manifeststaticfilesstorage

[SOCIALACCOUNT_PROVIDERS.google]
FOO = "bar"
